version: '3.8'

services:
  pgdb:
    image: postgres:15.8
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - "./postgres.sql:/docker-entrypoint-initdb.d/init.sql"
  mysql:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    restart: always
    volumes:
      - "./mysql.sql:/docker-entrypoint-initdb.d/init.sql"